#!/bin/sh
#
# Start xinetd
#

start() {
	start-stop-daemon -q -S -p /var/run/xinetd.pid -x /usr/sbin/xinetd -- -pidfile /var/run/xinetd.pid
}

stop() {
	start-stop-daemon -q -K -p /var/run/xinetd.pid
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
